
@ARTICLE {,
    author = "Ershov Bogdan Anatolievich, Fursov Vladimir Nikolaevich",
    title  = "RUSSIAN ORTHODOX CHURCH IN THE STRUCTURE OF STATE ADMINISTRATION IN THE XIX - BEGINNING XX centuries",
    year   = "2017",
    volume = "5",
    pages  = "47-58",
    month  = "sep",
    note   = "Abstract. The article outlines the key areas of the charitable and educational activities of the Orthodox Church, which are analyzed during religious reforms in the 19th and early 20th centuries. in Russia. It is shown that at that time the scale of charity aid and the responsibilities of charitable organizations increased; the control over the distribution of aid has improved, the role of the Church in the social protection of the population has increased.
        The conclusions made in the article allow us to look at a holistic picture of the Church's activities in providing the educational process in Russian church schools during the period under study. It turned out that the concrete activity of the clergy, which was impossible without the proper level of education, placed the clergy in the most literate category of the population. It is the priests, in the absence of a developed education system in Russia, began to introduce primary public education.
        This article helps to understand and systematize the position of the Church as a spiritual and moral institution that preserves Russia's cultural heritage.
Of particular importance is the regional nature of the topic under study, which makes it possible to understand the general and specific relations between the Church and the state.
         For the international community, the article will be useful as an archival exhibition, which is a rare publication that reveals the relationship between the Orthodox Church and the state in Russia in the 19th and early 20th centuries.


I. INTRODUCTION

In the XIX - early XX centuries. The Orthodox Church occupied an important place in the life of the Russian people. Priest A. Borisov spoke about the influence of the Church: \"The existence of the Russian Orthodox Church was for people a sign of the presence of God in the world\" [1]. The social role and functions of religion in the XIX century have changed a lot. The church was represented as a natural institution that plays a huge role in human life, raising spirituality over social, aesthetic and economic values. Due to significant changes in the country, relations between the church and the state have created new trends. 
The role of the Church began to prevail not only in the socio-cultural, but also in the political life of the Russian state. The Christian ideology of the Orthodox Church influenced the consciousness of Russian citizens. The Russian Orthodox Church is able to cultivate in a person such qualities as love for people, patience, compassion, mercy, honesty, modesty, respect for the interests of others, which constitutes the spiritual basis of the individual. An objective assessment of any event can not be given without a complete picture of the interaction of the Church and the state. In this regard, the Church can be described as a social organization [2]. 
On the one hand, the Church was a collection of communities, and on the other hand, it was a church hierarchy. In the modern era, the Church organically joined the civil society. Being a part of civil society, the Church has always been independent of the state and even competed with the state not only in the social sphere, but also in the spiritual sphere. Religion is the spiritual component of the Church. The ontology (the picture of the world) and the axiology (value system) offered by religion differed from the ideology of the state. Since the Church has always relied on tradition, it has been perceived as \"eternal\" and unchanging, beginning with its origins, and therefore it was an alternative to a \"changing\" world. 
The Church professed the image of the fidelity of tradition. Cultural beliefs, symbols and values were a sphere of religion, and they solved questions of human existence. Analyzing these historical facts, one can understand the particular urgency of this topic.


II. METHODOLOGY


The methods used in the article are traditional for historical works. In order to analyze the relationship between the Church and the state, a systematic method was used to comprehensively study the concepts and ideas of different scientists in order to compare these concepts with each other and emphasize their interrelationship and role. 
The process of relations between the Church and secular power in positive and negative development can be analyzed using the method of scientific objectivity and historicism, which made it possible to reveal that in the nineteenth and early twentieth centuries the incorporation of the Orthodox Church into the state administration of the Russian state was practically completed. The article uses a comparative-historical method that makes it possible to trace the development of Orthodoxy in Russia's public life, to show the features of the formation of the Church and society as a whole during this period. One can single out the method of synchronization, which makes it possible to trace the history of the development of missionary fraternities in the region, to reveal the peculiarities of their work, which consists in the opening of schools, libraries, reading rooms, sobriety societies. Another important method used in this article was the statistical method [9]. 
The statistical method allowed to confirm the results that were made when analyzing numerous unpublished and published materials. The digital data used in the article were taken from the materials of federal and regional archives. On the basis of information on the activities of the church and state structures contained in the archives, one can get a fairly clear idea of the number and financial condition of the parishes, the dynamics of the opening of churches and monasteries. 
The method of socio-psychological analysis made it possible to show the reasons for the activation of large masses of the population in the sphere of people's donations to the construction of Orthodox churches. This method also revealed the fact that the Church served as an important link in the social assistance system. The actualization method, based on the analysis of the results obtained, made it possible to make some forecasts and develop practical recommendations that would help solve the problems in the relations between the church and the state at the present time [8]. 
The use of different approaches and methods of scientific research made it possible to create a clear picture of the relationship between the state and the Church in the 19th and early 20th centuries. in Russia.

III. RESULTS

The Orthodox Church in the XIX century was an instrument of state policy, an institution that merged with state structures. The church was ruled by the Holy Synod and spiritual consistories. Although the Synod was an executive power and had no legislative initiative, he issued orders, which were to be performed by the spiritual departments. The composition of the Synod has changed, but in the XIX - early XX centuries. There were 10 bishops representing the black clergy, as well as the confessor of the emperor and the chief priest of the army and navy, who were representatives of the white clergy. Some members of the Synod were permanent, who were obliged to attend all meetings of the Synod: for example, the confessor of the emperor, the chief priest of the army and navy, Metropolitan of St. Petersburg; The temporary members took part in the Synod meetings once or twice a year [3]. 
The spiritual consistories were headed by bishops, they were appointed by the Synod and the emperor. The bishop, together with the spiritual consistory and with the support of the dean - the senior priests in the diocese - exercised administration and the court. The members of the spiritual consistory were representatives of the white and black clergy, who were elected bishop. As part of the consistories, the white clergy were represented better than in the Synod: in 1801 the parish priests accounted for 38% in the consistory, and in the 1860s. - 79%. The emperor himself supervised the work of the Chief Prosecutor of the Synod. But the control of the chief prosecutor was superficial, and therefore the spiritual consistories were controlled independently. The development of the institute of the Ober-Procuracy can be divided into two phases: the first - from the day of its appearance until 1803 the second phase began in 1817 and lasted until 1803-1817. until the end of the Synodal period [4]. 
Until 1803, the influence of the Chief Prosecutor had no decisive role in the work of the Synod, which was in direct contact with the emperor himself. Monasteries were ruled by monks. At the beginning of the reign of Alexander I the Synod consisted of five representatives of the black clergy. This composition was created by Catherine II. The church was one of the state ministries - \"the ministry of Orthodox confession\" - throughout the entire imperial period of Russian history. The Emperor received various proposals on the reform of the Church with regard to changing various aspects of her life. The highest political leadership understood that church reforms are necessary, and the emperor and his entourage are interested in strengthening Orthodoxy. In this connection, the experience of the General Directorate of Spiritual Affairs of Foreign Confessions and the Ministry of Spirituality and National Education is of great interest. The experience of creating such a double ministry was to include church authorities in the state structure, thereby realizing many ideas through education [5]. 
The initiator of the creation of these state institutions was the supreme power of the state in the person of Emperor Alexander I and his closest assistants, among whom the most important role in this process was played by A.N. Golitsyn, who was an active supporter of the inclusion of church authorities in state structures. In the difficult conditions of Russia's renewal, the clergy attempted to assume the role of an independent moral arbiter, insisting on overcoming class differences and appeasing social upheavals. The state of the church and state in Russia at the end of the nineteenth century was as follows: the Orthodox Church was deprived of independence because of custody and control over the state; disagreement in religion was brutally suppressed. However, the unification of the Church and the state was a boon for both sides, as it allowed each side to fully use its reserves for a dignified life [6]. 
Thus, summing up, it can be noted that the connection between the Church and the state was built in the XIX - early XX centuries. on the principle of subordination of the Church to state power. In fact, the Orthodox Church was one of the divisions of a ramified state apparatus. The emperor was the bearer and source of supreme authority in the Orthodox Church. The church was under the tutelage of state power, without a real possibility to act as an independent spiritual and moral force. However, it was a public legal institution that performed such functions as collection of statistical data, registration of acts of civil status, control over spiritual censorship and administration of justice. In addition, the Church was responsible for public education [7].

IV. DISCUSSION

Historiography of the problem of the relationship between the Russian Orthodox Church and the state in the nineteenth and early twentieth centuries. is divided into pre-revolutionary, Soviet and post-Soviet periods. In the pre-revolutionary period secular and ecclesiastical historians conducted significant work on the collection of materials and their publication. Basically, these materials had the nature of reference data and historical essays [12]. 
The content of some of them is still relevant today. In their studies, scientists talked about the difficulties of the parish clergy and tried to attract public attention to it. Historian P.V. Znamensky in his book studied the position of the clergy in the XIX century. He analyzed the legislation on the Church and played an important role in public events with regard to the clergy. P.V. Znamensky mainly studied materials on the central and southern dioceses. Historian D.I. Rostislavov analyzed the complex material situation of the clergy in his works, he was one of the first who drew attention to the incomes of clergymen and their economic activities. He paid considerable attention to the monastic economy. Work D.I. Rostislavova presents statistics on 290 monasteries. Historian P.N. Miliukov believed that the role of the Church and its social position depended on state power, the clergy was a closed class, and the believers were satisfied with sectarianism and the Old Believers. Mirsky devoted his work to the problems of the white clergy. It is noteworthy that the author tried to protect the moral state of the clergy in the eyes of society. He spoke about the need to transfer priests to the state salary. In the pre-revolutionary period, a lot of literature on the history of church law was published [15]. 
Among these works is allocated IG. Aivazov about the activities of the Orthodox faith during the reign of Emperor Alexander III and church-civil orders. These works contain information about the rights to clerical rights and their rights to use land. In the Soviet period of research on the history of the Russian Orthodox Church there was little. For the study of religion and the Church, the approach was ideological. The clergy turned out to be the exploiter of people. In the literature on the history of the Church during the Soviet period, tendentiousness prevailed, the pathos of denunciation prevailed, facts were often distorted. Despite the prevalence of publicism in the evaluation of church activity, scientific methods based on historical material are gradually beginning to penetrate. In the 1920s. the first generalizing studies on the history of the Church are published, in which some aspects of his activity in Soviet Russia were touched upon. 
Titlinov's work was more impartial. On the whole, the author examined the situation of the Russian Orthodox Church impartially, noting that the diocesan authorities did not care much for their moral obligations during the monarchical period, in fact being one of the structures of the power system that was expressed in the negative attitude of the clergy to the religious policy of the state. In Candidov's work \"The Church and 1905\" was given a significant source material, which allowed to identify the relationship of the tsarist regime with the Orthodox clergy. In the opinion of B.P. Candidova, in general, the activity of the church was counter-revolutionary in nature, most priests persistently supported the autocracy [18]. 
This work had a vivid political connotation. The main work of the Soviet historian V.I. Pisareva gives an objective assessment of the activities of the Orthodox Church in the Russian state. The author made conclusions about the crisis of the Church, about the increase in the Church's interference in state affairs, about the growth of the material welfare of the clergy. IN AND. Pisarev believed that the reforms of the 1860s lifted class restrictions in the formation of the clergy and changed the professional training of the clergy. 
Most modern scholars objectively approach the study of the history of the Orthodox Church. B.N. Mironov published a monograph \"The Social History of Russia in the Period of the Empire\", in which he examines the formation and development of the clergy in Russia. He believes that the spiritual state in Russia is completely independent in the state system. B.N. Mironov shows how the clergy from the estate turned into a professional group. 
These works contain various information about the history of the state and the Church. Some of these studies have a narrow topic, while others are limited to a time frame.
V. CONCLUSION

The Russian Orthodox Church linked its history with the history of the Russian state.  In this situation, the Church could influence political processes.  Relations between the state and the Russian Orthodox Church, which developed in the XIX century, did not always meet the requirements of Russia.  
It can be argued that, while respecting religion, some authorities accepted political dividends, but did not recognize religion as a fundamental sphere of public life.  The state, having subordinated the Church, destroyed the dependence of the spiritual from the secular, which led to the elimination of moral principles in society and internal strife.  The clergy recognized the merger of the Russian Orthodox Church and state.  The patronage of the Church through secular power prompted religious leaders to the necessity of church reforms.  The Russian Orthodox Church collided in the XIX - early XX centuries.  with the problems associated with the modernization of the state and society, which manifested itself in the weakening of the role of religion among the masses;  in the destruction of the patriarchal way of life;  in the development of sectarianism and atheistic sentiments [21].  
At the end of the XIX century, the Orthodox Church was able to create a significant system of religious enlightenment and a missionary capable of preserving the Orthodox traditions of the population in the provinces of the Central Chernozem region.  If, at the beginning of the nineteenth century, the spiritual and educational activities in the districts depended on the proximity of a large monastery or on the zeal of the parish clergy, then in the late 19th and early 20th centuries it became the norm for large villages and the city.  
The article shows that the Russian Orthodox Church, thanks to its intellectual abilities and social uplift, has become an influential social force, leaving a state of immobility and spiritual isolation from worldly worries.  
The Orthodox Church in Russia, despite all the difficulties: financial, political, social, managed to determine the main directions of religious education of the population.  Undoubtedly, the state was interested in church politics, but secular authorities tried to preserve their own interests in this policy.


REFERENCES

[1]. Ashmarov, I.A. (2011). Ways of modernization of the national economy of Russia. Voronezh: \"Science-UniPress\", 240 p.
[2]. Garanova, E.P., Kiskin, E.V. (2007). Legal regime of church property: inter-system collisions of canonical and secular law (1917-1929) // History of state and law, № 20, P. 19-21.
[3]. Dashkovskiy, P.K., Shershneva, E.A. (2016). Relations between the Muslim communities and the Russian Orthodox Church in Western Siberia in the second half of XIX – early XX century in the context of confessional policy of the Russian // Bylye Gody, Vol. 39, Is. 1.
[4]. Dikarev, V.N. (2002). Agrarian relations and property in the methodology of agrarian reform. Voronezh: VSAU, 232 p.
[5]. Dmitriev, S.S. (1966). Orthodox Church and State in the pre-reform period // History of the USSR, № 4, P. 52.
[6]. Dobrosklonsky, A.P. (2001). Guide to the history of the Russian Church. Moscow: Krutitskoe Patriarchal Compound, 569 p.
[7]. Eroshkin, N.P. (1981). The feudal autocracy and its political institutions (the first half of the 19th century). M.: Mysl, 274 p.
[8]. Ershov, B.A. (2012). Historiographical aspects of the relationship between the Russian Orthodox Church and state structures in the provinces of the Central Chernozem region in the XIX - early XX centuries. // Bulletin of the Voronezh State Technical University, T. 8, № 11, Pp. 188-192.
[9]. Firsov, S.L. (1998). The Financial Situation of the Russian Church in the Last Pre-Revolutionary Decade // The Church Historical Herald, №1, Pp. 145-161.
[10]. Kolesnikova, V.C. (2004). Brief encyclopaedia of Orthodoxy. Way to the temple. Moscow: Tsentrpoligraf, 589 p.
[11]. Kryvelev, I.A. (1982). Russian Orthodox Church in the first quarter of the XX century. M .: Knowledge, 64 p.
[12]. Kumova, L.I. (1992). Rural community in Russia (second half of the XIX century.). M.: Knowledge, 63 p.
[13]. Leontyeva, T.G. (2002). Faith and progress: the Orthodox rural clergy of Russia in the second half of the XIX-early XX centuries. M.: New chronograph, 272 p.
[14]. Lyubinetsky, I.A. (1900). Landholding of churches and monasteries of the Russian Empire. St. Petersburg. Parts 1-4.
[15]. Mitrokhin, N. (2002). Russian Orthodox Church as a Subject of Economic Activity // Issues of Economics, № 8, Pp. 8-9.
[16]. Monasteries and monasticism in Russia XI-XX century. Historical essays of the Institute of Russian History. (2002). Moscow: Nauka, 346 p.
[17]. Perevozchikova, L.S., Ershov, B.A., Ashmarov, I.A., Volkova, E.A. (2017). Role of Russian Orthodox Church in Life of Peasants in Russia in XIX - The Beginning of the XX-th Centuries // Bylye Gody, № 43 (1).
[18]. Pospelovsky, D.V. (1993). Russian Orthodox Church: trials of the early twentieth century // Questions of history, №. 1, Pp.42-54.
[19]. Semashko, A.G. (2007). State-church relations in the synodal period of the history of the Russian Orthodox Church // Actual problems of law in modern Russia. Collection of scientific articles. Issue. 4. Moscow: Gothic, Pp. 172-180.
[20]. Smolich, I.K. (1997). Russian Monasticism. 988-1917. Life and teaching. M.: Orthodox Encyclopedia, 606 p.
[21]. Znamensky, P.V. (2000). History of the Russian Church. Paris. M.: Grail, 466 p.
        [22]. Rybakova, S.N. (2009) Russian monasteries and temples. Journey to the holy places. 303 p."
}
